config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations', omniauth_callback: "users/omniauth_callbacks" }

  root to: 'application#index'
  get '/home', to: 'users#home', as: 'home'

  resources :games do
    resources :reviews
  end

  get '/games/:id/details', to: 'games#details'
  get '/games/:game_id/reviews/:id/content', to: 'reviews#content'
  get '/games/:id/game_data', to: 'games#game_data'
  get '/all_games/index', to: 'all_games#index', as: 'all_games'
  get '/all_games/:id/show', to: 'all_games#show', as: 'all_games_show'

  get '/users/sign_out', to: 'application#index'
  get '/users/index', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/games/:game_id/reviews/:id', to: 'reviews#destroy', as: 'delete_review'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_reader :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  has_attached_file :avatar, default_url: ':style/default.png', styles: { thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :games
  has_many :reviews

  def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
  end

  def level_up
    self.gameview_level += 1
    self.save
  end

  def level_down
    self.gameview_level -= 1
    self.save
  end

  def level
    level = []
    case self.gameview_level
      when 0
      level = "Newbie"
      when 1, 2, 3
      level = "Beginner Gamer"
      when 4, 5, 6
      level = "Average Gamer"
      when 7, 8, 9
      level = "Advanced Gamer"
      when 10
      level = "Power Gamer"
      end
      return level
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :disable_flash

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @user }
    end
  end

end

app/views/users/_links.html.erb
<% if user.id === 1 %>
  <h3 class="text-center"><%= link_to 'Back', users_index_path %> | <a href="#" class="js-next-user" data-id="<%= @user.id %>">Next User</a></h3>
  <% else %>
  <h3 class="text-center"><a href="#" class="js-previous-user" data-id="<%= @user.id %>">Previous User</a>
    | <%= link_to 'Back', users_index_path %>
    | <a href="#" class="js-next-user" data-id="<%= @user.id %>">Next User</a></h3>
<% end %>

app/views/users/home.html.erb
<div id="masthead">
  <div class="container">
      <div class="row">
        <div class="">
          <h1>Welcome to GameView
            <p class="lead"><%= current_user.email %></p>
          </h1>
        </div>

  </div><!--/container-->
</div><!--/masthead-->
<!--main-->
   <div class="container">
     <div class="row">

       <br></br>

       <br></br>

         <div class="">
           <div class="row">
             <div class="col-md-8">
               <div class="panel panel-default">
                 <div class="panel-heading"><h3><%= link_to 'My Games', games_path %></h3></div>
                 <div class="panel-body">

                    <%= render :partial => 'games/list_games', locals: {games: current_user.games}  %>
                    <br></br>
                    <%= link_to "[Add Game]", new_game_path %>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading"><h3>GameView Level</h3></div>
                  <div class="panel-body">
                    <%= image_tag(current_user.avatar.url(:thumb)) %>
                    <h3><%= current_user.level %>
                    <br></br>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

          <br></br>

            <br></br>
            <div class="panel panel-default">
              <div class="panel-heading"><h3>My Reviews</h3></div>
                <div class="panel-body">
            <p>
                <%= render :partial => 'reviews/list_reviews'%>
                <br></br>
            </p>

            <br></br>
            </div>
          </div>

           </div><!--/right-->
     	</div><!--/row-->
   </div><!--/container-->

app/views/users/index.html.erb
<h1>Users</h1>

<br></br>

  <div>
    <% @users.each do |user| %>
        <p><h3><%=link_to user.email, user %></h3></p>
    <% end %>
  </div>
<br>

app/views/users/show.html.erb
<%= image_tag(@user.avatar.url(:thumb)) %>

<h2><%= @user.email %>'s Profile</h2>
<br>
<h4><%= @user.reviews.count%> Reviews:</h4>

<% if @user.reviews.empty? %>
   <h2><%= @user.email %> doesn't have any reviews!</h2>
   <% else %>
      <div>
        <% @user.reviews.each do |review| %>
          <h3><strong><%= review.title %></strong></h3>
          <h4><em><%= review.game.title %></em></h4>
          <p><%= review.content %></p>
        <% end %>
  <% end %>
 </div>

<br>
<hr>

<%= link_to 'Back', users_index_path %>