config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations', omniauth_callback: "users/omniauth_callbacks" }

  root to: 'application#index'
  get '/home', to: 'users#home', as: 'home'

  resources :games do
    resources :reviews
  end

  get '/games/:id/details', to: 'games#details'
  get '/games/:game_id/reviews/:id/content', to: 'reviews#content'
  get '/games/:id/game_data', to: 'games#game_data'
  get '/all_games/index', to: 'all_games#index', as: 'all_games'
  get '/all_games/:id/show', to: 'all_games#show', as: 'all_games_show'

  get '/users/sign_out', to: 'application#index'
  get '/users/index', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/games/:game_id/reviews/:id', to: 'reviews#destroy', as: 'delete_review'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/all_games_controller.rb
class AllGamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @games = Game.all
    @game = Game.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @games }
    end
  end


  def game_data
    @game = Game.find(params[:id])
    render :json => @game
  end

end

app/helpers/all_games_helper.rb
module AllGamesHelper
end

app/views/all_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Games</h1>
<hr>

<% @games.each do |game|%>
  <h4><strong><%= link_to game.title, all_games_show_path(game) %></strong></h4>
  <br>
  <% end %>

<%= link_to 'Back', home_path %>

<br>

app/views/all_games/show.html.erb
<p id="notice"><%= notice %></p>

  <h3 class="gameTitle"><%= @game.title %></h3>
    <br>
    <p><strong>Developer:</strong><div class="gameDeveloper"><%= @game.developer %></p></div>
    <br>
    <p><strong>Genre: </strong><div class="gameGenre"><%= @game.genre%></p></div>
    <br>
    <p><strong>ESRB Rating: </strong><div class="gameRating"><%= @game.esrb_rating%></p></div>
    <br>
    <p><strong>Players: </strong><div class="gamePlayers"><%= @game.is_multiplayer?%></p></div>
    <br>

    <br>
    <button class="js-next-game" data-id="<%= @game.id %>">Next Game...</button>
    <br>
    <br>
    <br>

  <%= link_to 'Back', games_path %>