config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations', omniauth_callback: "users/omniauth_callbacks" }

  root to: 'application#index'
  get '/home', to: 'users#home', as: 'home'

  resources :games do
    resources :reviews
  end

  get '/games/:id/details', to: 'games#details'
  get '/games/:game_id/reviews/:id/content', to: 'reviews#content'
  get '/games/:id/game_data', to: 'games#game_data'
  get '/all_games/index', to: 'all_games#index', as: 'all_games'
  get '/all_games/:id/show', to: 'all_games#show', as: 'all_games_show'

  get '/users/sign_out', to: 'application#index'
  get '/users/index', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/games/:game_id/reviews/:id', to: 'reviews#destroy', as: 'delete_review'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :disable_flash, :load_game, only: [:index, :show, :new, :edit, :update, :destroy, :content]

  def show
    @review = @game.reviews.find(params[:id])
  end

  def index
    @reviews = @game.reviews
    render json: @reviews, status: 200
  end

  def new
    @review = @game.reviews.build
    respond_to do |format|
      format.html
      format.xml  { render :xml => @review }
    end
  end

  def edit
    @review = @game.reviews.find(params[:id])
  end

  def create

    @game = Game.find(params[:game_id])
    @review = current_user.reviews.build(review_params)
    current_user.level_up

    respond_to do |format|
      if @review.save
        format.html { redirect_to([@review.game, @review], :notice => 'Review was successfully created.') }
        format.json  { render :json => @review, :status => :created }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @review.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @review = @game.reviews.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(review_params)
        format.html { redirect_to([@review.game, @review], :notice => 'Review was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @review.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @review = @game.reviews.find(params[:id])
    @review.destroy
    current_user.level_down

    respond_to do |format|
      format.html { redirect_to(home_path) }
      format.xml  { head :ok }
    end
  end

  def content
    review = Review.find(params[:id])
    @game_id = params[:id]
    render plain: review.content
  end

private

  def load_game
    @game = Game.find(params[:game_id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :game_id, :user_id)
  end

end

app/views/reviews/_form.html.erb
<%= form_for([game, review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <%= f.hidden_field :game_id, :value => game.id %>
  <div class="actions">
  <id="submitReview"><%= f.submit %>
  </div>
<% end %>

app/views/reviews/_list_reviews.html.erb
<% if current_user.reviews.empty? %>
  <%= "There aren't any reviews to display. Check out some recent reviews by other users:" %>
  <% @recent_reviews.each do |review| %>
    <p><h3><strong><%=review.title %></strong></h3></p>
    <p><em><%= review.content %></em></p>
    <p>Review for "<%= review.game.title%>"</p>
  <% end %>
<% else %>
  <% current_user.reviews.each do |review|%>
    <p><h3><strong><%=link_to review.title, game_review_path(review.game, review) %></strong></h3></p>

    <p><strong>Review for "<%= link_to review.game.title, game_path(review.game)%>"</strong></p>
    <br>
    <div id="content-<%= review.id %>">
      <p><em><%= truncate review.content %></em></p>
    </div>
    <br>
    <button id="<%= review.id %>" class="js-review-more" data-id="<% review.id %>">Read More...</button>
    <div id="<% review.game.id %>" class="hidden"><%= review.game.id %></div>
    <hr>

  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render partial: 'form'%>


<%= link_to 'Show', [@review.game, @review] %> |
<%= link_to 'Back', home_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_game_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_game_review_path %>

app/views/reviews/new.html.erb
<div id="reviewForm">
<h1>New Review</h1>

<%= render :partial => 'reviews/form', locals: { review: @reiew, game: @review.game } %>
</div>

<%= link_to 'Back', home_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="reviewTitle"><%= @review.title %></h1>
<h2 class="gameTitle"><%= @game.title %></h2>
<h3 class="reviewContent"><%= @review.content %></h3>

<br>

<em><%= link_to "Load Game Details", game_path(@game), :class => "load_game" %></em>
<div class="gameShow">

</div>

<br>
<hr>


<%= link_to 'Edit', edit_game_review_path(@review.game, @review) %> |
<%= link_to 'Delete', delete_review_path(@review.game, @review), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', home_path %>