config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { sessions: 'sessions', registrations: 'registrations', omniauth_callback: "users/omniauth_callbacks" }

  root to: 'application#index'
  get '/home', to: 'users#home', as: 'home'

  resources :games do
    resources :reviews
  end

  get '/games/:id/details', to: 'games#details'
  get '/games/:game_id/reviews/:id/content', to: 'reviews#content'
  get '/games/:id/game_data', to: 'games#game_data'
  get '/all_games/index', to: 'all_games#index', as: 'all_games'
  get '/all_games/:id/show', to: 'all_games#show', as: 'all_games_show'

  get '/users/sign_out', to: 'application#index'
  get '/users/index', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'
  delete '/games/:game_id/reviews/:id', to: 'reviews#destroy', as: 'delete_review'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
   <%= content_tag(:p, value, :class => "flash alert alert-#{key}") %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      &nbsp;

    </div>
      <div class="navbar-left navbar-brand" href="<%= root_path %>"><a class="navbar-brand">GameView</a></div>
      <div class="collapse navbar-collapse" id="navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% else %>
          <li><%= link_to 'Users', users_index_path %></li>
          <li><%= link_to 'All Games', all_games_path %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Home', home_path %></li>
              <li><%= link_to 'My Games', games_path %></li>
              <li><%= link_to 'Profile', edit_user_registration_path %></li>

              <li class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_home_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      &nbsp;

    </div>
      <div class="navbar-left navbar-brand" href="<%= root_path %>"><a class="navbar-brand">GameView</a></div>
      <div class="collapse navbar-collapse" id="navbar-collapse-1">

    
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>GameView</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="text-center">

        <% if current_page?(root_path) %>
          <%= render 'layouts/home_header' %>
        <% else %>
          <%= render 'layouts/header' %>
        <% end %>

        <%= render "layouts/flash" unless @disable_flash %>

        <br> <br />


        <%= yield %>

        <br> </br>


      </div>
      </div>

    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>

  </body>
</html>